Repository newrelic/infrastructure-agent-ansible, pull requests merged in 2021-07, with the labels that each got.

#109 Update meta
  meta/main.yml
Labels: ansible, documentation, hero

#106 Prevent errors on tarball install when using defaults
  tasks/install_targz.yml
Labels: ansible, hero

#105 Lock timeout supplement
  README.md
  defaults/main.yml
  tasks/install_dist_pkgs.yml
Labels: ansible, hero

#107 Ensure log dir exists
  tasks/install_dist_pkgs.yml
Labels: ansible, hero

#81 installing in a disabled state works for windows hosts
  tasks/install_dist_pkgs.yml
  tasks/install_targz.yml
Labels: ansible, help wanted, hero, triaged

#110 Update Changelog.md
  CHANGELOG.md
Labels: ansible, hero

#112 Add new way of creating newrelic-infra.yml to ensure that vault variables are read
  tasks/install_dist_pkgs.yml
  tasks/install_targz.yml
Labels: ansible, hero

#111 Add Stop and Start service instructions for tarball installation
  tasks/install_targz.yml
Labels: ansible, hero
